version: '3'
services:
  app:
    restart: always
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    command: sh -c './wait-for database:3306 -- npm run init:prod && npm run start:prod'
    depends_on:
      - database
  database:
    image: mysql:5.7.27
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=game_store
    ports:
      - 3306:3306

networks:
  default:
    driver: bridge
